tf:
  frozenModelPath: inception-v3/inception_v3_2016_08_28_frozen.pb
  labelsPath: inception-v3/imagenet_slim_labels.txt
  outputLayer: InceptionV3/Predictions/Reshape_1
  image:
    width: 299
    height: 299
    mean: 0
    scale: 255

spring.http.multipart.max-file-size: 5MB
fst:
  frozenModelPath: D:\\data\\robot_auto_seller\\robot_auto_seller_20171025(release)\\robot_inference_graph\\frozen_inference_graph.pb
  labelsPath: D:\\data\\robot_auto_seller\\robot_auto_seller_20171025(release)\\config\\label.txt
  image:
    width: 800
    height: 600
    mean: 0
    scale: 255
	